### ISSUE TITLE
Error with access token

### ISSUE THREAD

**Issue by eduhcano** [jasper-lu/facebook-ddp#1]
Hi @jasper-lu I'm getting the  "no matching login attempt" error too, so I've installed your **accounts-facebook-ddp** package and this branch of ObjectiveDDP.
However, in  _logonWithOAuthAccessToken_ when I make the httprequest with the FBsession accessToken, in my server I get the error:

> (oauth_server.js:398) Error in OAuth Server: Failed to complete OAuth handshake with Facebook. failed [400] {"error":{"message":"(#100) You must provide an app access token or a user access token that is an owner or developer of the app","type":"OAuthException","code":100}}

Any help on this?

**Comment by jasper-lu** [comment]
Ah I think I may have forgotten to push the latest version of the package to atmosphere. I'll do it now

**Comment by jasper-lu** [comment]
Hm, that's weird. Are you sure you're using the correct access token?

I do a security check on the access token by querying https://graph.facebook.com/app?access_token={your_access_token} to make sure that the app ids match. Can you try filling in your access token there to see if it will work?

**Comment by eduhcano** [comment]
Sure, but I'm away from my computer right now, I'll check it as soon as I can, thanks!

**Comment by eduhcano** [comment]
I have checked the token with  https://graph.facebook.com/app?access_token={your_access_token} and it was right because I have obtained the information from my app and with https://graph.facebook.com/me?access_token={your_access_token} I have obtained the user information.
So I decided to install the package locally to debug and something strange happened, when I run a copy of your package locally, the error is gone.
Maybe the packet in atmosphere is different from this version ?
